from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional


@dataclass(frozen=True)
class OutputFormat:
    suite: str          # e.g. "parboil"
    type: str           # "text" or "binary"
    dtype: Optional[str] = None  # e.g. "float32", "int32"
    endian: str = "little"
    atol: float = 0.0
    rtol: float = 0.0
    suffix: str = ".txt"

    @property
    def is_binary(self) -> bool:
        return self.type == "binary"


OUTPUT_SPECS: Dict[str, OutputFormat] = {
    "cutcp": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="float32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".dat",
    ),
    "sad": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="uint16",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".bin",
    ),
    "histo": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="uint8",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".bmp",
    ),
    "lbm": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="float32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".dat",
    ),
    "mri-gridding": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "mri-q": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".out",
    ),
    "sgemm": OutputFormat(
        suite="parboil",
        type="text",
        dtype="float32",
        endian="little",
        atol=1e-5,
        rtol=1e-5,
        suffix=".txt",
    ),
    "spmv": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="float32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".out",
    ),
    "stencil": OutputFormat(
        suite="parboil",
        type="binary",
        dtype="float32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".out",
    ),
    "pathfinder": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="int32",
        endian="little",
        atol=1.0,
        rtol=1.0,
        suffix=".txt",
    ),
    "particlefilter": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-5,
        rtol=1e-5,
        suffix=".txt",
    ),
    "myocyte": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "lud": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "leukocyte": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "kmeans": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-5,
        rtol=1e-5,
        suffix=".txt",
    ),
    "lavaMD": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "hotspot3D": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1.0,
        rtol=1.0,
        suffix=".txt",
    ),
    "hotspot": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1.0,
        rtol=1.0,
        suffix=".txt",
    ),
    "heartwall": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "cfd": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "backprop": OutputFormat(
        suite="rodinia",
        type="binary",
        dtype="float32",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "matmul": OutputFormat(
        suite="codee",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "coulomb": OutputFormat(
        suite="codee",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "pi": OutputFormat(
        suite="codee",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-5,
        rtol=1e-5,
        suffix=".txt",
    ),
    "atmux": OutputFormat(
        suite="codee",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "aes": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "basicmath-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-6,
        rtol=1e-6,
        suffix=".txt",
    ),
    "bitcount-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "qsort-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "susan-s-mibench": OutputFormat(
        suite="mibench",
        type="binary",
        dtype="uint8",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".pgm",
    ),
    "dijkstra-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".dat",
    ),
    "patricia-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "stringsearch-mibench": OutputFormat(
        suite="mibench",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "canneal-parsec": OutputFormat(
        suite="parsec",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "susan-e-mibench": OutputFormat(
        suite="mibench",
        type="binary",
        dtype="uint8",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".pgm",
    ),
    "susan-c-mibench": OutputFormat(
        suite="mibench",
        type="binary",
        dtype="uint8",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".pgm",
    ),
    "bfs-bulk-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "bfs-queue-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "fft-strided-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "fft-transpose-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "gemm-blocked-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "gemm-ncubed-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "kmp-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "md-grid-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "md-knn-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "nw-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "sort-merge-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "sort-radix-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "spmv-crs-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "spmv-ellpack-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "stencil-2d-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "stencil-3d-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "viterbi-mach": OutputFormat(
        suite="machsuite",
        type="text",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".data",
    ),
    "bfs": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "b+tree": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "bilateral": OutputFormat(
        suite="rodinia",
        type="binary",
        dtype="uint8",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".bin",
    ),
    "nw": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".txt",
    ),
    "streamcluster": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=1e-5,
        rtol=1e-5,
        suffix=".txt",
    ),
    "srad_v1": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="int32",
        endian="little",
        atol=0.1,
        rtol=0.1,
        suffix=".pgm",
    ),
    "srad_v2": OutputFormat(
        suite="rodinia",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.1,
        rtol=0.1,
        suffix=".txt",
    ),
    "tpacf": OutputFormat(
        suite="parboil",
        type="text",
        dtype="float64",
        endian="little",
        atol=0.0,
        rtol=0.0,
        suffix=".out",
    ),
    "haccmk": OutputFormat(
        suite="codee",
        type="text",
        dtype="float64",
        endian="little",
        atol=200.0,  # Allow ~100 absolute difference (observed validation differences)
        rtol=0.0,
        suffix=".txt",
    ),
}


def get_output_format(benchmark: str) -> Optional[OutputFormat]:
    return OUTPUT_SPECS.get(benchmark)


def suite_for_benchmark(benchmark: str) -> Optional[str]:
    fmt = OUTPUT_SPECS.get(benchmark)
    return fmt.suite if fmt else None

