#include <stddef.h>
#include <string.h>
#include <limits.h>
#include <time.h>
#ifdef _OPENMP
#include <omp.h>
#endif

static size_t table[UCHAR_MAX + 1];
static size_t len;
static char *findme;
static double strsearch_kernel_time_acc = 0.0;

void reset_strsearch_kernel_time(void) { strsearch_kernel_time_acc = 0.0; }
double get_strsearch_kernel_time(void) { return strsearch_kernel_time_acc; }

void init_search(const char *string)
{
      size_t i;

      len = strlen(string);
      for (i = 0; i <= UCHAR_MAX; i++)                      /* rdg 10/93 */
            table[i] = len;
      for (i = 0; i < len; i++)
            table[(unsigned char)string[i]] = len - i - 1;
      findme = (char *)string;
}

char *strsearch(const char *string)
{
      size_t shift = 1; /* initialize to non-zero to avoid UB before first use */
      size_t pos = len - 1;
      char *here = NULL;
      char *result = NULL;
      size_t limit = strlen(string);
      struct timespec kernel_start, kernel_end;

      clock_gettime(CLOCK_MONOTONIC, &kernel_start);

      /* Main search loop: kept serial to preserve timing and avoid race
         conditions on shared globals without changing the API. */
      while (pos < limit)
      {
            /* Use a tighter inner loop with local variables to help the
               compiler optimize and reduce repeated work. */
            const unsigned char *ustr = (const unsigned char *)string;
            const size_t *restrict t = table;
            const size_t local_len = len;

            while (pos < limit &&
                   (shift = t[ustr[pos]]) != 0)
            {
                  pos += shift;
            }

            if (shift == 0)
            {
                  here = (char *)&string[pos - local_len + 1];
                  if (0 == strncmp(findme, here, local_len))
                  {
                        result = here;
                        break;
                  }
                  /* Advance at least one character to avoid re-checking
                     the same position. */
                  ++pos;
            }
      }

      clock_gettime(CLOCK_MONOTONIC, &kernel_end);
      strsearch_kernel_time_acc += (kernel_end.tv_sec - kernel_start.tv_sec) +
                                   (kernel_end.tv_nsec - kernel_start.tv_nsec) / 1e9;
      return result;
}

#include <stdio.h>
#include <stdlib.h>

/* Configuration structure for different benchmark sizes */
typedef struct {
    const char *name;
    int num_searches;  /* Number of search iterations to perform */
} BenchmarkConfig;

/* Predefined size configurations */
static const BenchmarkConfig SIZE_CONFIGS[] = {
    {"mini",        1},      /* 1 iteration (current default) */
    {"small",       5000},     /* 50 iterations */
    {"medium",      20000},    /* 200 iterations */
    {"large",       80000},    /* 800 iterations */
    {"extra-large", 320000},   /* 3200 iterations */
};

static const int NUM_CONFIGS = sizeof(SIZE_CONFIGS) / sizeof(SIZE_CONFIGS[0]);

/* Get configuration by name */
static const BenchmarkConfig* get_config(const char *size_name) {
    int i;
    for (i = 0; i < NUM_CONFIGS; i++) {
        if (strcmp(SIZE_CONFIGS[i].name, size_name) == 0) {
            return &SIZE_CONFIGS[i];
        }
    }
    return NULL;
}

/* Print usage information */
static void print_usage(const char *prog_name) {
    int i;
    fprintf(stderr, "Usage: %s <size>\n", prog_name);
    fprintf(stderr, "Available sizes:\n");
    for (i = 0; i < NUM_CONFIGS; i++) {
        fprintf(stderr, "  %-12s : %d search iterations\n", 
                SIZE_CONFIGS[i].name, SIZE_CONFIGS[i].num_searches);
    }
}

int main(int argc, char *argv[])
{
      char *here;
      const BenchmarkConfig *config;
      int iteration, i;
      struct timespec main_start, main_end;
      FILE *timing_file = stderr;
      const char *timing_path = getenv("TIMING_LOG_FILE");
      double kernel_time = 0.0;
      double main_time = 0.0;
      int status = 0;
      
      clock_gettime(CLOCK_MONOTONIC, &main_start);
      reset_strsearch_kernel_time();

      /* Parse command-line arguments */
      if (argc != 2) {
          print_usage(argv[0]);
          status = 1;
          goto timing_cleanup;
      }
      
      config = get_config(argv[1]);
      if (!config) {
          fprintf(stderr, "Error: Unknown size '%s'\n", argv[1]);
          print_usage(argv[0]);
          status = 1;
          goto timing_cleanup;
      }
      
      char *find_strings[] = { "Kur",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
"gent",
"lass",
"suns",
"for",
"xxx",
"long",
"have",
"where",
"xxxxxx",
"xxxxxx",
"pense",
"pow",
"xxxxx",
"Yo",
"and",
"faded",
"20",
"you",
"bac",
"an",
"way",
"possibili",
"an",
"fat",
"imag",
"th",
"wor",
"xxx",
"xxx",
"yo",
"bxx",
"wo",
"kind",
"4",
"idle",
"Do",
"scare",
"people",
"wit",
"xxx",
"xxx",
"Th",
"xxx",
"yourself",
"Forget",
"succeed",
"Kee",
"lov",
"yo",
"Stretc",
"what",
"life",
"kno",
"wha",
"xxx",
"xxx",
"40",
"Get",
"xxx",
"them",
"Maybe",
"may",
"you",
"the",
"your",
"congratulate",
"much",
"either",
"are",
"Enjoy",
"it",
"be",
"other",
"it",
"xxx",
"greatest",
"own",
"nowhere",
"room",
"you",
"beauty",
"feel",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"xxx",
"it",
"Northern",
"before",
"Accept",
"Politicians",
"get",
"size",
"reasonable",
"their",
"Dont",
"support",
"trust",
"spouse",
"one",
"too",
"time",
"careful",
"with",
"Dispensing",
"past",
"the",
"parts",
"more",
"me",
NULL};
      char *search_strings[] = { "Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen",
"Kurt Vonneguts Commencement Address at",
"MIT Ladies and gentlemen of",
"the class of 97 Wear",
"sunscreen If I could offer",
"you only one tip for",
"the future sunscreen would be",
"it The longterm benefits of",
"sunscreen have been proved by",
"scientists whereas the rest of",
"my advice has no basis",
"more reliable than my own meandering experience",
"I will dispense this advice",
"now Enjoy the power and beauty",
"of your youth Oh never mind",
"You will not understand the power",
"and beauty of your youth until theyve",
"faded But trust me in",
"20 years",
"youll look",
"back at photos of yourself",
"and recall in a",
"way you cant grasp now how much",
"possibility lay before you",
"and how fabulous you really looked You",
"are not as fat",
"as you imagine Dont worry about",
"the future Or",
"worry but know that worrying is as effective",
"as trying to solve an algebra equation",
"by chewing bubble gum The real troubles in",
"your life are apt to",
"be things that never crossed your",
"worried mind the",
"kind that blindside you at",
"4 pm on some",
"idle Tuesday",
"Do one thing every day that",
"scares you Sing Dont be reckless with other",
"peoples hearts Dont put up",
"with people who are reckless",
"with yours Floss Dont waste your time",
"on jealousy Sometimes youre ahead sometimes youre behind",
"The race is long and in",
"the end its only with",
"yourself Remember compliments you receive",
"Forget the insults If you",
"succeed in doing this tell me how",
"Keep your old",
"love letters Throw away",
"your old bank statements",
"Stretch Be kind to your knees",
"Youll miss them when theyre gone Maybe youll marry maybe you",
"wont Maybe youll have children maybe",
"you wont Maybe youll divorce at",
"40 maybe youll dance the funky",
"chicken on your 75th wedding anniversary Whatever you",
"do dont congratulate yourself too",
"much or berate yourself either",
"Your choices are half chance",
"So are everybody elses",
"Enjoy your body Use it every way you can Dont",
"be afraid of",
"it or what other people think of",
"it Its the",
"greatest instrument youll ever own Dance even if you have nowhere",
"to do it but in your own",
"living room Read the directions even",
"if you dont follow them",
"Do not read beauty magazines They will",
"only make you feel ugly Get to know",
"your parents You never know when theyll be gone for",
"good Be nice to your siblings Theyre your best link to your",
"past and the people most likely to stick",
"with you in the future Understand that friends come and",
"go but for the precious few you should hold on Work",
"hard to bridge the gaps in geography",
"and lifestyle because the older you",
"get the more you need the people you knew when",
"you were young Live in New York City once but leave",
"before it makes you hard Live in",
"Northern California once but leave before it",
"makes you soft Travel Accept certain",
"inalienable truths Prices will rise Politicians will philander You too will get old",
"and when you do youll fantasize that when you were young prices were",
"reasonable politicians were noble and children respected their elders Respect",
"your elders Dont expect anyone else to",
"support you Maybe you have a trust",
"fund Maybe youll have a wealthy",
"spouse but you never know when either",
"one might run out Dont mess",
"around with your hair or by the",
"time youre 40 it will look 85 Be",
"careful whose advice you buy but be patient",
"with those who supply it Advice is a",
"form of nostalgia Dispensing it is",
"a way of fishing the past from",
"the disposal wiping it off painting",
"over the ugly parts",
"and recycling it for more than its",
"worth But trust me on the sunscreen"
};

      /* Perform multiple iterations as specified by config */
      for (iteration = 0; iteration < config->num_searches; iteration++) {
          for (i = 0; find_strings[i]; i++) {
                init_search(find_strings[i]);
                here = strsearch(search_strings[i]);
                printf("\"%s\" is%s in \"%s\"", find_strings[i],
                      here ? "" : " not", search_strings[i]);
                if (here)
                      printf(" [\"%s\"]", here);
                putchar('\n');
          }
      }

      status = 0;

timing_cleanup:
      clock_gettime(CLOCK_MONOTONIC, &main_end);
      kernel_time = get_strsearch_kernel_time();
      main_time = (main_end.tv_sec - main_start.tv_sec) +
                  (main_end.tv_nsec - main_start.tv_nsec) / 1e9;
      if (timing_path && timing_path[0] != '\0') {
          FILE *tmp = fopen(timing_path, "w");
          if (tmp) {
              timing_file = tmp;
          }
      }
      fprintf(timing_file, "KERNEL_TIME: %.9f\n", kernel_time);
      fprintf(timing_file, "TOTAL_TIME: %.9f\n", main_time);
      if (timing_file != stderr) {
          fclose(timing_file);
      }
      return status;
}

